title: Sushovan Majhi
email: sush@smajhi.com
description: This is Sushovan Majhi's personal homepage.
baseurl: ""
url: "https://www.smajhi.com"
github_username: sushovan4

# Build settings
include: [CNAME]  
markdown: kramdown	
theme: minima		
plugins:		
  - jekyll-multiple-languages-plugin
  - jekyll-feed
  - jekyll-sitemap	
languages: ["en", "bn"]
exclude_from_localizations: ["javascript", "images", "css"]
collections:
  research-projects:
    output: true
  teaching:
    output: false
  software-projects:
    output: false
  talks:
    output: false

defaults:
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "research-projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: tag
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Sushovan Majhi
