project:
  type: website
  preview: 
    port: 8080

website:
  repo-url: https://github.com/sushovan4/sushovan4.github.io
  repo-actions: [issue]
  favicon: assets/favicon.png
  page-navigation: true
  reader-mode: true

  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - file: tutorials/index.qmd
      - file: solutions/index.qmd

  page-footer: 
    right: "© 2022 Sushovan Majhi 〈sush@smajhi.com〉"
    border: true
    background: dark

  sidebar: 
    - id: munkres
      style: docked
      background: dark
      contents: 
        - section: "Solutions"
          href: solutions
          contents: 
            - section: "EAT"
              href: solutions/Munkres
              contents: solutions/Munkres/**

    - id: ml
      contents:
        - section: "Solutions"
          href: solutions
          contents: 
            - section: "FoML"
              href: solutions/ML
              contents: solutions/ML/*

format:
  html:
    theme: 
      light: journal
      dark: darkly
    css: 
      - css/styles.css
    code-fold: true
    toc: false
    code-copy: hover
    highlight-style: breeze
    code-link: true
    html-math-method: katex
    include-in-header: 
      - file: js/script.js
    
execute: 
  freeze: auto