project:
  type: website
  resources:
    - "assets/ornament.svg"
  preview:
    port: 8080

website:
  repo-url: https://github.com/sushovan4/sushovan4.github.io
  repo-actions: [issue]
  favicon: assets/favicon.png
  page-navigation: true

  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
          - href: research/index.qmd
            text: Projects
          - href: research/publications/index.qmd
            text: Publications
      - href: teaching/index.qmd
        text: Teaching
      - href: talks.qmd
        text: Talks
    right:
      - href: tutorials/index.qmd
        text: Tutorials
      - href: assets/cv.pdf
        text: CV
  page-footer:
    left: |
      <span class="footer-loc">Washington, D.C.</span>
    center: |
      <span class="footer-dept">Data Science &middot; The George Washington University</span>
    right: |
      <span class="footer-copy">© MMXXVI Sushovan Majhi</span>
    border: true
    background: light

bibliography: references.bib
csl: ieee-with-url.csl

format:
  html:
    theme: journal
    css:
      - css/styles.css
      - css/signature.css
    code-fold: true
    toc: false
    code-copy: hover
    highlight-style: breeze
    code-link: true
    html-math-method: katex
    include-in-header:
      - text: |
          <script type="text/javascript" src="/js/script.js"></script>
execute:
  freeze: auto
