project:
  type: website
  preview: 
    port: 8080

website:
  repo-url: https://github.com/sushovan4/sushovan4.github.io
  repo-actions: [issue]
  favicon: assets/favicon.png
  page-navigation: true
  reader-mode: true

  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: research/publications/index.qmd
    right:
      - href: tutorials/index.qmd
        text: Tutorials
      - href: solutions.qmd
  page-footer: 
    right: "© 2023 Sushovan Majhi 〈sush@smajhi.com〉"
    border: true
    background: dark

bibliography: references.bib
format:
  html:
    theme: 
      light: journal
      dark: darkly
    css: 
      - css/styles.css
    code-fold: true
    toc: false
    code-copy: hover
    highlight-style: breeze
    code-link: true
    html-math-method: katex
    include-in-header:
      - text: |
          <script type="text/javascript" src="/js/script.js"></script>
execute: 
  freeze: auto