project:
  type: website

  
website:
  repo-url: https://github.com/sushovan4/sushovan4.github.io
  repo-actions: [edit, issue]
  logo: assets/favicon.png
  page-navigation: true
  reader-mode: true
    
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: tutorials/index.qmd
    
  page-footer: 
    right: "© 2021 Sushovan Majhi 〈sush@smajhi.com〉"
    border: true
    background: dark

  sidebar:
    - id: smith
      border: true
      contents:
        - text: Smith Normal Form
          href: tutorials/topology/smith/index.qmd
        - text: Introduction
          href: tutorials/topology/smith/introduction.md
        - text: Normal Form
          href: tutorials/topology/smith/normal-form.md
        - text: Elementary Operations
          href: tutorials/topology/smith/ops.qmd
        - text: Algorithm
          href: tutorials/topology/smith/algo.qmd
        - text: Recution in Action
          href: tutorials/topology/smith/reduction-action.qmd
    - id: something-else
      title: else

format:
  html:
    theme: 
      light: journal
      dark: darkly
    css: 
      - css/styles.css
    code-fold: true
    toc: true
    code-copy: hover
    highlight-style: breeze
    code-link: true


