name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - run: |
          echo 'www.smajhi.com' >> CNAME 
          git add .
          git commit -m "add CNAME"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
